[tox]
envlist =
  py313-{pytest,lint,invalidcode,mypy}
  format
  format-check
  docs
skipdist = True

[testenv]
usedevelop = True
passenv = *
extras = tests
deps =
  py313-pytest: .[tests]
  py313-lint: flake8
  py313-invalidcode: flake8
  py313-mypy: mypy >= 0.900
commands =
  py313-pytest: pytest {posargs} -c pytest.ini
  py313-lint: flake8 moulinette tests
  py313-invalidcode: flake8 moulinette tests --select F
  py313-mypy: mypy  --ignore-missing-imports --install-types --non-interactive moulinette/

[gh-actions]
python =
  3.13: py313

[testenv:format]
basepython = python3
commands = black {posargs} moulinette tests
deps = black
skip_install = True
usedevelop = False

[testenv:format-check]
basepython = {[testenv:format]basepython}
commands = black {posargs:--check --diff} moulinette tests
deps = {[testenv:format]deps}
skip_install = {[testenv:format]skip_install}
usedevelop = {[testenv:format]usedevelop}

[testenv:docs]
basepython = {[testenv:format]basepython}
usedevelop = True
commands = python3 -m sphinx -W doc/ doc/_build
deps =
  -r{toxinidir}/doc/requirements.txt
